/*
CrudSQL API

Testing SchemaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/ilyassjmyi/CRUDSQL-GO-SDK"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_SchemaAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SchemaAPIService ModelSchemaGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var model string

		resp, httpRes, err := apiClient.SchemaAPI.ModelSchemaGet(context.Background(), model).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
