/*
CrudSQL API

A powerful dynamic CRUD API engine that automatically generates RESTful endpoints for your data models CrudSQL provides automatic CRUD operations, filtering, pagination, and sorting capabilities for any data model. Features: - Automatic REST API generation - Dynamic model support - Complex filtering and querying - Pagination and sorting - Swagger documentation - Multiple database support (SQL & NoSQL)

API version: 1.0.0
Contact: taqi@mobix.biz
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiRelationshipSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRelationshipSchema{}

// ApiRelationshipSchema Schema information for a model relationship
type ApiRelationshipSchema struct {
	// Name of the relationship
	Name *string `json:"name,omitempty"`
	// Name of the related model
	RelatedModel *string `json:"relatedModel,omitempty"`
	// Type of relationship (hasOne, hasMany)
	Type *string `json:"type,omitempty"`
}

// NewApiRelationshipSchema instantiates a new ApiRelationshipSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRelationshipSchema() *ApiRelationshipSchema {
	this := ApiRelationshipSchema{}
	return &this
}

// NewApiRelationshipSchemaWithDefaults instantiates a new ApiRelationshipSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRelationshipSchemaWithDefaults() *ApiRelationshipSchema {
	this := ApiRelationshipSchema{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiRelationshipSchema) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRelationshipSchema) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiRelationshipSchema) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiRelationshipSchema) SetName(v string) {
	o.Name = &v
}

// GetRelatedModel returns the RelatedModel field value if set, zero value otherwise.
func (o *ApiRelationshipSchema) GetRelatedModel() string {
	if o == nil || IsNil(o.RelatedModel) {
		var ret string
		return ret
	}
	return *o.RelatedModel
}

// GetRelatedModelOk returns a tuple with the RelatedModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRelationshipSchema) GetRelatedModelOk() (*string, bool) {
	if o == nil || IsNil(o.RelatedModel) {
		return nil, false
	}
	return o.RelatedModel, true
}

// HasRelatedModel returns a boolean if a field has been set.
func (o *ApiRelationshipSchema) HasRelatedModel() bool {
	if o != nil && !IsNil(o.RelatedModel) {
		return true
	}

	return false
}

// SetRelatedModel gets a reference to the given string and assigns it to the RelatedModel field.
func (o *ApiRelationshipSchema) SetRelatedModel(v string) {
	o.RelatedModel = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiRelationshipSchema) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRelationshipSchema) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiRelationshipSchema) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiRelationshipSchema) SetType(v string) {
	o.Type = &v
}

func (o ApiRelationshipSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRelationshipSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RelatedModel) {
		toSerialize["relatedModel"] = o.RelatedModel
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiRelationshipSchema struct {
	value *ApiRelationshipSchema
	isSet bool
}

func (v NullableApiRelationshipSchema) Get() *ApiRelationshipSchema {
	return v.value
}

func (v *NullableApiRelationshipSchema) Set(val *ApiRelationshipSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRelationshipSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRelationshipSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRelationshipSchema(val *ApiRelationshipSchema) *NullableApiRelationshipSchema {
	return &NullableApiRelationshipSchema{value: val, isSet: true}
}

func (v NullableApiRelationshipSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRelationshipSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


